### ISSUE TITLE
Does it require Emacs master (post-28) `subr` ?

### ISSUE THREAD

**Issue by gagbo** [bitspook/notes-migrator#2]
I had to manually evaluate 

```lisp
(defalias 'pos-bol #'line-beginning-position)
(defun delete-line ()
  "Delete the current line."
  (delete-region (pos-bol) (pos-bol 2)))
```
in order to run the `org-roam` -> `denote` script, otherwise I hit `(void-function delete-line)`, even after I manually `(require 'subr)` on my Emacs 28.1 build (with the pgtk patches applied, installed from flatwhatson guix channel)

**Comment by bitspook** [comment]
I run emacs 29 (using nix [emacs-overlay](https://github.com/nix-community/emacs-overlay)), so I suppose yes. I should've tested with 28 and/or mentioned in readme the versions with which I've tested the script.

Thank you for bringing this to my notice.
