### ISSUE TITLE
Convertion fails with `Wrong type argument: org-roam-node, nil`

### ISSUE THREAD

**Issue by jloow** [bitspook/notes-migrator#5]
I'm trying to convert my org-roam notes to denote. The process fails with the message `Wrong type argument: org-roam-node, nil`. The backtrace looks like this:

```
Debugger entered--Lisp error: (wrong-type-argument org-roam-node nil)
  signal(wrong-type-argument (org-roam-node nil))
  (or (progn (and (memq (type-of node) cl-struct-org-roam-node-tags) t)) (signal 'wrong-type-argument (list 'org-roam-node node)))
  (progn (or (progn (and (memq (type-of node) cl-struct-org-roam-node-tags) t)) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1))
  (string-match-p "daily" (progn (or (progn (and (memq (type-of node) cl-struct-org-roam-node-tags) t)) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1)))
  (lambda (node) (string-match-p "daily" (progn (or (progn (and (memq ... cl-struct-org-roam-node-tags) t)) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 1))))(nil)
  cl-remove(nil (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) :if (lambda ... ...))
  apply(cl-remove nil (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) :if (lambda ... ...) nil)
  cl-remove-if((lambda ... ...) (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...))
  (let* ((roam-nodes (mapcar #'nm--roam-node-from-file (org-roam-list-files))) (notes (cl-remove-if #'(lambda (node) (string-match-p "daily" (progn ... ...))) roam-nodes)) (dailies (cl-remove-if-not #'(lambda (node) (string-match-p "daily" (progn ... ...))) roam-nodes))) (mapcar #'nm--migrate-roam-node notes) (if (and dailies-tag (not (string-empty-p (string-trim dailies-tag)))) (progn (mapcar #'(lambda (n) (nm--migrate-roam-node n (list dailies-tag))) dailies))))
  nm-migrate-org-roam-to-denote("")
  funcall-interactively(nm-migrate-org-roam-to-denote "")
  call-interactively(nm-migrate-org-roam-to-denote record nil)
  command-execute(nm-migrate-org-roam-to-denote record)
  execute-extended-command(nil "nm-migrate-org-roam-to-denote" nil)
  funcall-interactively(execute-extended-command nil "nm-migrate-org-roam-to-denote" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Org-roam version is 2.2.2
Emacs version is 28.2
I'm on macOS

**Update:** I tried creating a new org-roam folder and made few new notes. The convertion then completes without any error. It seems some of my notes are causing the issue.

**Update 2:** The error seems to occur when there are subdirectories in the org-roam folder; after removing the subdirectories I was able to convert my files.

**Comment by bitspook** [comment]
Thanks for reporting this @jloow I'll look into this.

**Comment by bitspook** [comment]
@jloow Can you help me a bit to replicate this issue please? I created a new note in org roam using `org-roam-node-find`, and moved it to a subdirectory in my `org-roam-directory`. After that I executed following script:

```lisp
(load-file "./nm-org-roam-to-denote.el")

(let ((denote-directory "/tmp/denotes/"))
  (nm-migrate-org-roam-to-denote))
```

All the notes, including the note in subdirectory in `org-roam-directory` were migrated without any errors, although the sub-directory was lost (i.e the note I had as `<org-roam-directory>/<subdir>/note.org` was migrated to `<denote-directory>/note.org`). Was there anything else you were doing that might have caused this error? 

From the backtrace it looks like the script encountered a file which wasn't an org-roam node. Any chance you have some file in org-roam which don't have a `PROPERTIES` drawer on top of the file?

**Comment by jloow** [comment]
I've run some more tests. The problem, I think, is that I do not only have org-files in my org-roam folder. For example, I keep my templates in a subdirectory in that folder and I attach things to many of my notes. It seems you are correct; it's not the folders but the non-org-roam files. Removing images, pdfs etc. seems to solve the issue.

Would it be possible to have the script ignore non-org-roam files?

**Comment by bitspook** [comment]
It should ignore them actually, and it does in my case. I also have subdirectories for images and they cause no problem in migrating the notes (although they are not copied over with migrated notes). Can you please make sure you have the latest code (by doing a `git pull` in this repo)?

**Comment by jloow** [comment]
Maybe I'm missing some steps in my tests. There also also some html files
in the directory (the result of exporting some notes). Could that be
causing the error?

If not, I'll see if I can narrow it down in the weekend.

**Comment by bitspook** [comment]
No, html files isn't it. Just checked.

**Comment by jloow** [comment]
Now I've identified which specific file**s** (there were more than one being problematic) cause the conversion to fail.

1. A file named `inbox.org` with ID `ef6fa0d2-5d6c-496a-99b7-e15c8c3afa5d`. It is located in the root org-roam directory.
2. A files that has a name in the form of `authorYEAR.org` with ID `2D69B644-8C4F-4DEC-9CDC-DBE59051CF1A`. It is located in a subfolder called `references`. The file is generated by `citar-org-roam`.
3. The template files that I use for `org-roam`. The files have no ID and have names such as "default.org". They are located in a folder named `templates`.

The conversion does not fail if I have an ordinary org file (that is, no ID, no particular naming convention) in a data folder. Are data folders ignored? (By data folder I mean those folders created by org attach.) In such case, I assume the error is due to the files not following the naming convention?

**Comment by bitspook** [comment]
Migration script uses `org-roam-list-files` to get a list of org-roam files to migrate. It then goes through each of these files, trying to collect their ID from `PROPERTIES` drawer at top of the file. So if there are files which aren't provided by `org-roam-list-files`, which I assume would be any non-org files as well as the atachments directory. 

So we heavily piggy-back on the functionality org-roam provides. 

>  Are data folders ignored?

Yes. 

>  I assume the error is due to the files not following the naming convention?

Yes and no. If org-roam thinks that it need to take in a file, but can't (e.g becuase it don't follow a naming convention), migration script will also throw an error. But as per my testing, that error isn't the same as presented in the stack trace you provided. In this case, I am getting this error: `(error "Encountered org-roam file with unknown name: inbox.org")`.
But this also means that if org-roam can read this file without error, migration script shouldn't have a problem either.

I have pushed a small fix to simply ignore the org fiels org-roam consider valid but which don't have an ID in a PROPERTIES drawer at the top. I don't think this will fix your problem, but the original error you posted should be remedied with this.

**Comment by jloow** [comment]
> But as per my testing, that error isn't the same as presented in the stack trace you provided.

Yes, you are correct. I missed, sorry!

> I have pushed a small fix to simply ignore the org fiels org-roam consider valid but which don't have an ID in a PROPERTIES drawer at the top. I don't think this will fix your problem, but the original error you posted should be remedied with this.

I'm perfectly fine with this. Thanks for all your support!
