### ISSUE TITLE
Update Project About

### ISSUE THREAD

**Issue by jgarte** [bitspook/notes-migrator#7]
(only org-roam to denote supported for now) 

But logseq is supported ;()

**Comment by bitspook** [comment]
Done! 
Thank you for the reminder @jgarte!

**Comment by jgarte** [comment]
anytime!

I'm planning to package it for guix: 

https://todo.sr.ht/~whereiseveryone/guixrus/1241

**Comment by bitspook** [comment]
Awesome! Let me know if I can help in any way! One of these days I gotta start with Guix.

**Comment by jgarte** [comment]
> Awesome! Let me know if I can help in any way! One of these days I gotta start with Guix.

Sure, would you like to send a patch for notes-migrator?

TLDR:

```sh
git clone https://git.sr.ht/~whereiseveryone/guixrus
cd guixrus
EDITOR guixrus/packages/emacs.scm
# Add your package in that file
guix build emacs-notes-migrator -L .
git add guixrus/packages/emacs.scm
git commit
git send-email -1 --to="~whereiseveryone/guixrus@lists.sr.ht"
```

I can upstream the patch for you later or feel free to ask me more questions about how to do that.

guixrus is a pre-release channel maintained by the whereiseveryone community:

https://whereis.みんな/

We have a custom channel package search here:

https://toys.whereis.みんな/

**Comment by bitspook** [comment]
Sure let me give it a shot! This'd be my first time sending a patch via email. (I didn't know git had a `send-email` command 🤯 )

**Comment by jgarte** [comment]
Cool! I'll look out for the patch.

See this education website on how to set up `git send-email`:

https://git-send-email.io/

**Comment by bitspook** [comment]
I managed to install guix in an Arch VM on MacOS (unfortunately the OS I am using these days), got the `guix build emacs-notes-migrator -L .` working, and sent the mail using `git send-mail -1`.  It will probably end up in your spam folder. 

Please let me know if I need to fix/change something. 

This whole workflow feels so weird 😅 

---

Btw, thank you for letting me do this. I had a long time standing TODO item for trying out Guix. I haven't read any documentation and know pretty-much nothing about Guix, but at least I now have a working installation to play with. I wish Guix worked on MacOS.

**Comment by bitspook** [comment]
There is CI for patches from mail https://lists.sr.ht/~whereiseveryone/guixrus/patches/39374

This is so cool 🤯

**Comment by jgarte** [comment]
@bitspook 

Thanks for sending the patch and contributing to Guix and Guix 'R Us!

[unmatched-paren](https://git.sr.ht/~unmatched-paren/) applied it:

https://lists.sr.ht/~whereiseveryone/guixrus/patches/39374

;()

If you're [subscribed](https://git.sr.ht/~whereiseveryone/guixrus#subscribing) to Guix 'R Us and do a `guix pull` you should now have `emacs-notes-migrator` package available to install:

`guix install emacs-notes-migrate`

Or see our instructions on how to install packages from Guix 'R Us [without subscribing](https://git.sr.ht/~whereiseveryone/guixrus#without-subscribing).
