### ISSUE TITLE
nm--roam-node-denote-id: Symbol’s value as variable is void: denote--id-format

### ISSUE THREAD

**Issue by juh2** [bitspook/notes-migrator#8]
I get this error when I try to run nm-migrate-org-roam-to-denote:

nm--roam-node-denote-id: Symbol’s value as variable is void: denote--id-format

I am running
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-08-02, modified by Debian
org-roam 2.2.1.

**Comment by bitspook** [comment]
Thanks for reporting the bug @juh2 

I have pushed a fix to the exact error you reported; hopefully it should fix the problem. However I haven't created reproducible setup with versions you reported. So please take a new pull and do report back how it works. 😅

**Comment by juh2** [comment]
Yes, it works. Thanks a lot.
