### ISSUE TITLE
Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer  *temp*> (fundamental-mode)

### ISSUE THREAD

**Issue by domsch1988** [bitspook/notes-migrator#9]
I'm trying to move Roam -> Denote.
org-roam-directory and denote-directory are both set. I have just about 20 roam, org files. There is already one denote file present. Both directories are different from each other. It seems like it's putting out this error per file.

![image](https://github.com/bitspook/notes-migrator/assets/1961154/72847060-ab32-4a1a-9f5c-6088cef57fbf)

I'm on emacs 29.3, org 9.7-pre and org-roam 2.2.2
I migrated my roam notes to v2 (even if they should have already been).
Let me know if i can provide any further details.

**Comment by bitspook** [comment]
Thanks for reporting the issue @domsch1988! 

Until I can  find some time to set up a test env to fully replicate this, can you please checkout to [gh-issue-9](https://github.com/bitspook/notes-migrator/tree/gh-issue-9) branch and try? This should fix the immediate issue you reported above.

**Comment by domsch1988** [comment]
So, this fix worked, but i ran into an issue where `denote-slugify` was expecting a `COMPONENT` in addition to the string. I replaced that with `denote-slugify-string` and it work. Function now looks like this.
```
(defun nm--roam-node-denote-filename (node)
  "Return valid denote file name for org-roam NODE."
  (let* ((id (nm--roam-node-denote-id node))
         (tags (mapcar #'downcase (org-roam-node-tags node)))
         (title (or (string-replace "/" "-" (org-roam-node-title node)) "untitled")))
    (concat id "--" (denote-sluggify-title title) "__" (string-join tags "_") ".org")))
```

I've made #11  for that change against the branch for this issue.

**Comment by bitspook** [comment]
Thanks a lot! I'll merge #10 then!
